### PR TITLE
Upgrade to Quarkus 3

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
@agoncal any chance you could merge this (once CI is green) and release a new major version before April 25th?

**Comment by gsmet** [comment]
Ah I see you didn't release anything yet so it's not really required to do a release.

**Comment by majguo** [comment]
@gsmet The PR looks great, thanks for upgrading to Quarkus 3! I merged the PR and it also fixes the CI build failure, see [Quarkus ecosystem CI](https://github.com/quarkiverse/quarkus-azure-services/actions/runs/5076257701). Regarding to the release, I'm working on this and will let you know once it's ready to go.

**Review by majguo — COMMENTED** [review]
LGTM

**Comment by majguo** [comment]
@all-contributors please add @gsmet for code

**Pull request merged**
