### PR TITLE
Support filtering by labels for App Configuration extension

### LINKED ISSUE #153: Support labels for App Configuration extension
Introduce configuration property for selecting list of labels.

### PR DESCRIPTION
**Pull request by fhavel**
Closes #153

### CODE REVIEW

**Review by majguo — CHANGES_REQUESTED** [review]
Hello @fhavel Thanks for your contribution! I was busy with other things recently, so sorry for the late response. The code changes look good. Would you pls also update doc/code sample/test script to cover your changes?
* https://github.com/quarkiverse/quarkus-azure-services/blob/main/integration-tests/README.md
* https://github.com/quarkiverse/quarkus-azure-services/blob/main/integration-tests/azure-app-configuration/README.md
* https://github.com/quarkiverse/quarkus-azure-services/tree/main/integration-tests/azure-app-configuration
* https://github.com/quarkiverse/quarkus-azure-services/blob/main/.github/build-with-maven-native.sh

**Comment by fhavel** [comment]
Hi @majguo 
I have added the requested changes. As for testing with an external service, I haven't been able to do that because I don't currently have access to Azure to create a new Resource Group. Could you please kindly assist with that by testing it? Thank you!

**Comment by majguo** [comment]
Hello @fhavel Thank you for your contribution! Sure, I will test it with an external Azure service next week and let you know the result.

**Comment by majguo** [comment]
Hello @fhavel Today I got chance to run pipeline in my fork with your changes against real Azure services, two issues are found and fixed, you can cherry-pick these fixes from [my fork](https://github.com/majguo/quarkus-azure-services).
* [Imports are not sorted](https://github.com/majguo/quarkus-azure-services/actions/runs/7483682486/job/20369328199)
  * Fix: https://github.com/majguo/quarkus-azure-services/commit/d1d0b5c592bdc155ecc04badd991ee3ba549b804
*  [Fail if there are uncommitted changes](https://github.com/majguo/quarkus-azure-services/actions/runs/7483752957/job/20369504900)
  * Fix: https://github.com/majguo/quarkus-azure-services/commit/3026615c60ed4d4d03be9bb34f562c37b93b796b

**Comment by fhavel** [comment]
Hello @majguo I have updated it. Thank you for support.

**Review by majguo — APPROVED** [review]

**Comment by majguo** [comment]
Hello @fhavel Could you pls locally run the following commands and commit changes if any?
1. mvn-Bcleaninstall-Dno-format
1. mvn-Binstall-Dnative-Dquarkus.native.container-build-Dnative.surefire.skip

**Comment by fhavel** [comment]
@majguo There was some whitespace missing, sorry for that

**Comment by majguo** [comment]
@all-contributors please add @fhavel for code

**Pull request merged**
