### PR TITLE
Upgrade Azure SDK BOM to version 1.2.19

### PR DESCRIPTION
**Pull request by oscerd**
This should upgrade the SDK BOM correctly

- Azurite needs to be upgraded to latest version 3.28.0
- ConfigurationSettingPage in Azure-data-appconfiguration in Azure Java SDK has been remove moving from 1.4.x to 1.5.x

All tests are green locally

### CODE REVIEW

**Comment by oscerd** [comment]
This should also solve a CVE related to reactor-netty version.

**Review by majguo — APPROVED** [review]
@oscerd  LGTM, thanks for your fix.

**Comment by oscerd** [comment]
I'll double check the native build later.

**Comment by oscerd** [comment]
Should be fine now.

**Comment by majguo** [comment]
@all-contributors please add @oscerd for code

**Pull request merged**
