### PR TITLE
Simplify app-configuration tests

### PR DESCRIPTION
**Pull request by ppalaga**
Could you please review @radcortez ?

I still wonder why the test application outputs these warnings?

```
[INFO] 2022-12-06 22:56:05,053 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.azure.app.configuration.secret" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
[INFO] 2022-12-06 22:56:05,055 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.azure.app.configuration.id" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
[INFO] 2022-12-06 22:56:05,056 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.azure.app.configuration.endpoint" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

### CODE REVIEW

**Comment by radcortez** [comment]
Hum, it seems we have a bug reporting the Unrecognized properties in the static Config when the mapping is runtime only, and the configuration is only available at runtime. I'll have to check and fix this on the Quarkus side.

**Comment by ppalaga** [comment]
Is this good to merge @agoncal ?

**Comment by agoncal** [comment]
Thanks @ppalaga @radcortez

**Comment by majguo** [comment]
@all-contributors please add @ppalaga for code

**Comment by majguo** [comment]
@all-contributors please add @radcortez for review

**Pull request merged**
